data:
  input_path: "data/retail_store_data.csv"
  output_path: "data/processed/"

model:
  arima_order: (1,0,0)
  save_path: "models/saved/sales_forecast.pkl"

features:
  numeric_cols:
    ["price", "instock", "totalstock", "sales", "stockleft", "revenue"]
  date_col: "Date"
  target: "sales"

logging:
  level: "INFO"
  path: "logs/app.log"
