
name: Sales Automation AI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Daily retraining

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort pytest pytest-cov
      - name: Lint
        run: |
          black .
          isort . 
      - name: Test
        run: |
          python -m pytest tests/ --cov=models --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3

  train:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python main.py
      - name: Save model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/saved/*.pkl
            models/metrics.json

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
      - name: Check metrics
        run: |
          python models/evaluate.py
          if [ $? -eq 0 ]; then
            echo "::set-output name=deploy::true"
          fi
